import os
os.system("sudo ufw enable")
os.system("sudo apt update")
os.system("sudo apt install")
os.system("sudo apt-get update")
os.system("sudo apt get upgrade")
os.system("sudo apt install curl")
choice=input("Do you want to delet all .mp3 files? Y N")
if choice = "Y":
	os.system("sudo find / -name '*.mp3' -type f -delete 2>/dev/null")
os.system("sudo updatedb")
os.system("cd /etc")
os.system("sudo curl -s https://raw.githubusercontent.com/cheesenranch8/CyberScript/main/autoupgrade | sudo tee /etc/apt/apt.conf.d/20auto-upgrades > /dev/null")
os.system("sudo sed -i 's/^PASS_MAX_DAYS\s*99999/PASS_MAX_DAYS  30/' /etc/login.defs")
os.system("sudo systemctl stop nginx")
os.system("sudo systemctl disable nginx")
os.system("sudo apt remove ophcrack -y")
os.system("sudo apt remove wireshark -y")
os.system("sudo apt remove wireshark -y")
os.system("sudo apt autoremove -y")
os.system("sudo sed -i 's/^PermitRootLogin\s*yes/PermitRootLogin no/' /etc/ssh/sshd_config")
